spring.application.name=servidorlocal

spring.datasource.url=jdbc:h2:file:./data/servidorlocal
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

server.max-http-header-size=128KB
server.tomcat.max-http-form-post-size=2MB

spring.h2.console.enabled=true

# Configuracoes do servidor de Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=barbosahifb1997@gmail.com
spring.mail.password=tiackgqamqfaxmgy

# Configurações avançadas de seguramça exigidas pelo Gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

